name: CTCI Solutions Integrity Check

on:
  paths:
    - 'CTCIPythonPlayground/src/*'
    - 'CTCIPythonPlayground/test/*'
  push:
    branches: [master, practice, config]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run CTCI Test Suite
        run: pytest -v
